### ISSUE TITLE
Conflict with Powertools Persistent Profiles

### ISSUE THREAD

**Issue by tatundria** [EmuDeck/MetaDeck#13]
**Expected Behaviour**
If I start for example Mario Kart 8 the Profile in Powertools should switch to Mario Kart 8 and apply/remember my configs. If I close Mario Kart 8 the Profile should go back to Main.

**Actual Behaviour**
When I start for example Mario Kart 8 the Profile in Powertools does stay on Main. It won't apply/remember any of my configs.

People found that it turns out that the issue had nothing to do with Powertools, it came from MetaDeck. I just uninstalled it and restarted Steam. Now everything works well again. 

Please, check the following link that describes the issue:
https://github.com/NGnius/PowerTools/issues/86

**Comment by KP2048** [comment]
This seems to either have been fixed or I just can't replicate it. Reopen if you are still having this issue
