### ISSUE TITLE
Non Steam Games in "Great on Deck"

### ISSUE THREAD

**Issue by SilentException** [EmuDeck/MetaDeck#2]
Happens from time to time, usually after selecting a game and going into the Game Info.
After returning to the library, previously viewed game might appear in Great on Deck tab.
It gets sorted out by itself, some kind of auto refresh I suppose.
I should also note that there were worse situations as well where all of the non Steam games would appear in Great on Deck.
I'm not familiar with Steam/Decky plugin system but I've seen in the code that this plugin strips some the game data properties so might be related to that. Sorry for the shitty video, hope it can be fixed. Thanks

https://user-images.githubusercontent.com/613606/213896874-96038541-5979-4ea4-ba7d-b3f07f3a45bf.mp4

**Comment by KP2048** [comment]
Lol, maybe a result of setting the deck verified sticker

**Comment by KP2048** [comment]
This is now a functional feature, non steam games that have compatibility data set and have the green checkbox show in the great on deck tab and don't glitch.
