### ISSUE TITLE
Consistently hangs, never loads

### ISSUE THREAD

**Issue by TheCyberQuake** [EmuDeck/MetaDeck#23]
Plugin never fully loads, consistently hangs on the same title. Can be left to load for hours but makes no progress.

Title:
Blinx: The Time Sweeper

Progress:
65/67

I get this issue on multiple EmuDeck plugins (the other notable one being Emuchievements, which hangs on a different title)
This issue has persisted across multiple Decky Loader versions, on both prerelease and stable, and has persisted across a full reimage.
I would greatly appreciate being pointed to any other details/logs I could grab that may help point us in the right direction to figuring out what's going on.

**Comment by TheCyberQuake** [comment]
Also of note, I'm running stable for Steam OS updates, on latest as of 6/28

**Comment by patrickkempff** [comment]
I have the same issue. It is hanging on 28/30 games. I tried to reboot, reinstall, update without any success.

**Comment by Fing3rSalad** [comment]
Same issue here,

**Comment by Andrew-R-Lawler** [comment]
The plugin is hanging on CEMU Metadeta consistently.

**Comment by Pherrera0** [comment]
Same issues here.

**Comment by windir19** [comment]
I'm having same issue. Stops on a game saying it can't find Metadata and won't keep going. Makes plugin not work at all waiting for it to load all the metadata.

**Comment by bymem** [comment]
Yup same here, did have some luck reloading the plug-in, and getting to go through some more games, but it just stops a little further then.

**Comment by cookandy** [comment]
Same issue here (version `2.0.1`). If i reinstall sometimes it will get further, but it never seems to finish.

**Comment by EASK8ER52** [comment]
Any update on if this will be fixed or if it's being worked on?

**Comment by TheCommandoChicken** [comment]
Is this gonna get fixed? It seems like this should be high priority since it literally breaks the entire plugin.

**Comment by bymem** [comment]
Seems like the project is dead.

**Comment by KenwoodFox** [comment]
Also having this issue... What can we do? What code might be relevant to review?

**Comment by indigofairyx** [comment]
in a year ive never once been able to use this plugin. it seems it runs in to a game with no meta info and it rather than skipping said game, it gets stuck there, forever, for a year. idk. ive tried looking at the setting code. i cant figure out how to skip a game with empty metadata. the code is over my head

ive tried hiding the games it gets stuck on, that no help, it still sees them and gets stuck.

ive gone a weeeeebit overboard on setting up my deck with over 350 games, roms, hacks, gogs, etc etc. i think i just have to forsake meta for another year

**Comment by EstrangeCade** [comment]
It looks as if the plugin is not generating any settings file for whatever reason. I would love to see this one working again as it's the last thing that I need to complete my setup :(

**Comment by danielsteiner** [comment]
Same for me. Reloading the plugin in decky settings helps a bit and it usually manages to fetch the data for the game where it was previously hanging. 

BUT: on large libraries it wont ever finish (I've been sitting constantly reloading the plugin for one hour now)

**Comment by EstrangeCade** [comment]
Link to the devs Discord if anyone is interested: https://discord.gg/tPwwKX5d

**Comment by KP2048** [comment]
I think I can confidently claim this is fixed in the testing store version. It also should pick up where it left off if it gets stuck again for some reason since it saves as it goes
