### ISSUE TITLE
SteamOS 3.5 support

### ISSUE THREAD

**Issue by lothar-cell** [EmuDeck/MetaDeck#26]
SteamOS 3.5 broke Metadeck, all other Decky plugin work. I'm hoping for an update (at some point).
Thanks for your work by the way:)

**Comment by proatgram** [comment]
Is there any update on this issue? I am experiencing issues on SteamOS > 3.5.

**Comment by lothar-cell** [comment]
There's a .zip on their Discord, which kinda works alright, but not perfect.

**Comment by TheBrokenG0d** [comment]
> There's a .zip on their Discord, which kinda works alright, but not perfect.

Got a link? I went on the EmuDeck Discord and couldn't find it.

**Comment by lothar-cell** [comment]
Ask it there.

**Comment by KP2048** [comment]
Version 3.0.0 on the testing store works

**Comment by lothar-cell** [comment]
Actually for me doesn't unfortunately:
![IMG_0807](https://github.com/user-attachments/assets/35657b15-5dc2-4852-9e97-70eb6d60a664)
All the while Metedeck's plugin page hangs saying "Fetching..."

**Comment by KP2048** [comment]
You aren't using decky v3. Update your decky version

**Comment by KP2048** [comment]
Also you need to update to the testing store version
