### ISSUE TITLE
Meta info lost after restarting Steam

### ISSUE THREAD

**Issue by AkazaRenn** [EmuDeck/MetaDeck#27]
Tested on desktop mode with Steam Big Picture, I believe it also happens in Game Mode by restarting the system.

Once the Steam client is restarted, all loaded meta information will be lost and needs to be loaded again, I think we can make some kind of a cache for it? And given it's not very critical information, it should be okay to be saved as plain texts, like a `json` or something.

**Comment by RudeBoyEEEE** [comment]
Any updates? I'm having this issue too.

**Comment by KP2048** [comment]
Fixed in 3.0.0
