### ISSUE TITLE
Plugin counts suspend time as in-game time

### ISSUE THREAD

**Issue by SuperGuerreiro** [EmuDeck/MetaDeck#3]
Hey, I've noticed that this issue happens with this plugin: if you suspend your non-Steam game, it will still count the time as if you were playing. I assume this isn't trivial to implement, but in order to mimic what the Deck does for Steam games natively, this should be integrated. 

My (uninformed) suggestion would be, if possible, to save a local timestamp of when the Deck was put to sleep, and later, have another timestamp of when it was awakened/powered on again. Then, calculate the elapsed time between the two timestamps and subtract it from the total time played (?)

Anyway, here are the steps to reproduce the issue:

    Start a non-Steam game, let it play for few seconds to reach the menu for easy quitting.
    Suspend the unit for however much time
    Wake up the unit, immediately close the game.

Thank you and good luck!

**Comment by KP2048** [comment]
This is fixed in playtimes plugin, MetaDeck doesn't track times anymore anyway
