### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by ghost** [EmuDeck/MetaDeck#30]
If i try to install Metadeck it will try to Load and Get info for all my Non-Steam titles. It will hang, Usually on a Title with a special Character such as : ,  and . Either that or it’s incredibly outdated, Refreshing the Plugin a ton doesn’t work

**Comment by KP2048** [comment]
Interesting, I know it's broken, but the special characters bit might help

**Comment by githubUser01946** [comment]
It still doesn't work and I'm using it with City of Heroes which is listed on IGDB which this plugin claims to use.

**Comment by KP2048** [comment]
This was fixed a while ago

**Comment by ghost** [comment]
> This was fixed a while ago

Well not really, because it doesn't load information for my non-steam titles

**Comment by kergoth** [comment]
This doesn't work for me at all still.
