### ISSUE TITLE
Plugin loops in "Fetching" screen

### ISSUE THREAD

**Issue by Stebo91** [EmuDeck/MetaDeck#33]
The steam logo keeps spinning in the "Fetching" screen and the plugin never actually starts downloading metadata.

**Comment by KP2048** [comment]
I'm in the process of a rewrite, so this should be fixed in the next release

**Comment by KP2048** [comment]
Sometimes reloading the plugin helps I've found. Need to get to the bottom of this as I experience this too sometimes. Especially when I deploy my plugin and restart the loader.

**Comment by KP2048** [comment]
This is fixed
