### ISSUE TITLE
MetaDeck not recording time

### ISSUE THREAD

**Issue by moostalo** [EmuDeck/MetaDeck#5]
Hi, I've used MetaDeck and I was enjoying its use.

However, after a while, I noticed there an issue when running my non-Steam games.
There was not a time recording. It did not register my time on the different games.
I've tried reinstalling a couple of times if it could fix it. I didn't see any changes.

Can you help me ?

Best regards

**Comment by knosuhor** [comment]
Same here, tried versions from testing store and default, also directly from github. Neither shows "play time".

**Comment by pondpondnaja** [comment]
Same here, I've tried reinstalling a couple of times but it still didn't record my play time(for new game) or change my play time.

My Decky version is : 2.6.4
My SteamOS Version is : 3.4.6

![5D53EE27E9E585DA2A4C588CAF282484273691DC](https://user-images.githubusercontent.com/44794453/229859424-5f5f1a1a-99ae-49d1-8772-0b9a3b9cacd8.jpeg)

**Comment by fidesachates** [comment]
Same here

**Comment by KP2048** [comment]
People. MetaDeck doesn't do playtimes anymore. That's the job of the playtimes plugin
