### ISSUE TITLE
Not working anymore 

### ISSUE THREAD

**Issue by AlbertoEberhardt** [EmuDeck/MetaDeck#6]
The plugin stop working after some Steam Client and Decky Loader updates ( it even doesn't appear on the shop page). Please update it!

**Comment by geenaxion** [comment]
Same here. Although i manage to find it on the testing store, but still doesn't record the time.
All previous time are gone.

Stable os.

**Comment by AlbertoEberhardt** [comment]
The dev said that this feature will be removed from Metadeck, and will be moved to the SDH-PlayTimes plugin as you can read [here](https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/285)
